TODO.md, docs/clouds/oci.md, docs/conf.py, docs/examples/oci.rst, examples/oci.py, pycloudlib/__init__.py, pycloudlib/cloud.py, pycloudlib/instance.py, pycloudlib/key.py, pycloudlib/oci/cloud.py, pycloudlib/oci/instance.py, pycloudlib/oci/utils.py, pycloudlib/util.py, requirements.txt
Also includes an additional commit for some small key handling refactors that I don't want squashed. Might make sense to review the two commits separately.
The API purposely doesn't completely line up with the base class (like many of the other implementing classes) but is taking the form that I would like the base class to use (in a separate soon-to-come PR). It should work as-is though.
=> Add oracle

pycloudlib/ec2/vpc.py
Before we can add subnets, we need to wait until the boto3 vpc
resource is available and reloaded before trying to setup subnets as
AmazonProvidedIpv6CidrBlock=True takes a little while to get
allocated to the VPC, and subnet creation relies on the dynamic
IPv6Cidr created.
=> ec2: add wait_until_available and reload after calling create_vpc

docs/clouds/azure.md, examples/az.py, pycloudlib/__init__.py, pycloudlib/azure/__init__.py, pycloudlib/azure/cloud.py, pycloudlib/azure/instance.py, pycloudlib/azure/util.py, pycloudlib/cloud.py, pycloudlib/ec2/util.py, pycloudlib/instance.py, pycloudlib/kvm/instance.py, pycloudlib/lxd/instance.py, pycloudlib/util.py, requirements.txt
This PR adds azure support to pycloudlib.
Right now, there are still some things to be completed:
* Define how to handle pro images
I will keep working on these details, but I think it is worth to collect feedback on the implementation I have so far.
Furthermore, this is test script I have been using to the test this new feature:
```python
import logging                                                                                                                                                                                                     
from pycloudlib.azure.cloud import Azure …
```
=> Add Azure support

pycloudlib/instance.py
Trusty doesn't have cloud-init status --wait. So use runlevel and results.json file test.
=> trusty: instance._wait_for_system uses runlevel due to dated cloud-init

pycloudlib/ec2/cloud.py
Add tags to any created snapshots for EC2
=> ec2: tag snapshots

examples/base_api.py, pycloudlib/cloud.py, pycloudlib/gce/cloud.py, pycloudlib/gce/instance.py, pycloudlib/gce/util.py, pycloudlib/instance.py
Expand the functionality of GCE so it roughly aligns with the functionality of the other clouds
=> Gce instance

requirements.txt, setup.py
=> pycloudlib: use PEP-508 format to specify simplestreams dependency

pycloudlib/instance.py, pycloudlib/tests/test_instance.py
This option allows consumers to configure whether or not `pycloudlib`
should raise an exception if cloud-init fails in the system being
launched.
=> BaseInstance: add raise_on_cloudinit_failure parameter to wait()

pycloudlib/tests/test_instance.py
This is the behaviour we observe on trusty, so the tests should cover
it.
=> test_instance: test that `cloud-init status --help` can return non-zero

pycloudlib/lxd/instance.py
When `raise_on_error` is false, we still need to wait until the LXD VM is ready and ignore some of these startup errors. Also adding `Error: Instance is not running` to the errors list
=> Add additional LXD VM error to ignore

pycloudlib/azure/instance.py, pycloudlib/lxd/instance.py
Azure and LXD need wait_for_stop implementations.
=> Add wait_for_stop implementations

.travis.yml, pycloudlib/lxd/defaults.py
This fixes #62 (though not in a long-term fashion, so I've opened #75 to
cover that).
=> lxd/defaults: add entries for groovy and hirsute

pycloudlib/azure/cloud.py, pycloudlib/azure/util.py, pycloudlib/util.py
- Add ability to make more granular changes to vm_params when creating
an instance
- When deprovisioning an image for snapshot generation,
add option to keep the original user instead of automatically
removing it
- Small bugfix to not throw exception if image offer is None
=> Some Azure updates

pycloudlib/azure/cloud.py
This enables the launching of hirsute instances.
Fixes: #90
=> azure: add hirsute to UBUNTU_RELEASE

pycloudlib/gce/cloud.py
Specifically: ignore it and set the `response` variable in a way that
allows us to retain a single exception generation code path.
Fixes #101
=> gce: ignore ConnectionResetError in _wait_for_operation

pycloudlib/openstack/__init__.py, pycloudlib/openstack/cloud.py
This fixes the import issue described in #126.
=> openstack: add __init__.py

pycloudlib/azure/instance.py, pycloudlib/gce/instance.py, pycloudlib/instance.py, pycloudlib/lxd/instance.py
See the commit messages for details.
=> Align LXDInstance's console_log behaviour with others (plus refactoring)

pycloudlib/lxd/instance.py
Xenial VMs do not have a lxd-agent, we can't see process
count for VMs.
Fallback to check lxc ls state as "RUNNING" on Xenial VMs.
Add LXDInstance.wait_for_state() method and adapt lxc.wait_for_stop
to use that shared method.
python3  examples/lxd.py  # watch for DEBUG:pycloudlib.instance:waiting for (STOPPED|RUNNING): pycloudlib-vm  logs
=> lxd.vm: check lxd ls state == RUNNING on xenial

pycloudlib/ec2/instance.py, pycloudlib/instance.py, pycloudlib/openstack/cloud.py, pycloudlib/openstack/instance.py, pycloudlib/openstack/tests/test_instance.py
Needed for integration testing https://github.com/canonical/cloud-init/pull/936
I expect there may some change in the base interface as new clouds are added.
=> Allow hotplug of NIC on Openstack and EC2 (SC-254)

pycloudlib/gce/instance.py, pycloudlib/lxd/instance.py, pycloudlib/oci/cloud.py, pycloudlib/oci/utils.py, pycloudlib/openstack/instance.py
Unrelated issues found in latest cloud-init SRU. See individual commits for specific details. Don't squash merge.
=> Sru issues (SC-373)

pycloudlib/oci/cloud.py
=> oci: ignore "GPU" images

Makefile, docs/Makefile, tox.ini
Includes:
* Docs build
* Share testenvs when reasonable
* Share common config when reasonable
* Bump linting versions
* Rename py3 env to pytest
* Remove nose section
* Remove default recreate=true
Also update main makefile clean to also clean docs dir and print docs
make commands to stdout.
=> update tox.ini (SC-674)

.git-blame-ignore-revs, examples/az.py, examples/base_api.py, examples/lxd.py, examples/oci.py, pycloudlib/azure/cloud.py, pycloudlib/azure/instance.py, pycloudlib/azure/tests/test_cloud.py, pycloudlib/azure/util.py, pycloudlib/cloud.py, pycloudlib/ec2/vpc.py, pycloudlib/gce/cloud.py, pycloudlib/gce/instance.py, pycloudlib/gce/util.py, pycloudlib/instance.py, pycloudlib/lxd/cloud.py, pycloudlib/lxd/defaults.py, pycloudlib/lxd/tests/test_defaults.py, pycloudlib/util.py, pyproject.toml, setup.py, tox.ini
Should have just done this at the same time as black.
As before, the config changes are separate commits so should be easier to review.
=> Isort (SC-701)

pycloudlib/azure/cloud.py
Also remove unsupported releases
=> Add impish to azure releases (SC-851)

pycloudlib/cloud.py, pycloudlib/gce/cloud.py, pycloudlib/tests/test_cloud.py
=> gce: expand ~user in credentials_path

pycloudlib/oci/cloud.py, pycloudlib/oci/instance.py, pycloudlib/oci/utils.py
topic: Factor out OCI get_subnet_id
=> Factor out OCI get_subnet_id

pycloudlib/azure/util.py
Azure recent identity changes no longer raise an error
related to CLI misconfiguration/absence on initial client creation.
We need to minimally perform an operation against the CLI to confirm
presence or absence of necessary CLI config or fallback to using the
ClientSecretCredential.
Add smoke test to attempt to list operations of the resource client
if credentials are unavailable catch the ClientAuthenticationError
and fallback to ClientSecretCredential.
=> azure: perform smoke test to validate CLI config

pycloudlib/azure/cloud.py, pycloudlib/ec2/cloud.py, pycloudlib/gce/cloud.py, pycloudlib/lxd/cloud.py, pycloudlib/lxd/tests/test_cloud.py, pycloudlib/oci/cloud.py, pycloudlib/openstack/cloud.py
Let's be a bit more noisy about expected input values.
=> launch: assert image_id non None on all clouds

docs/design.rst, setup.py
Port doc/design.md to RST to natively render tables.
setup.py: increase minimum python version to 3.6.
=> doc: add explanation about python support

.python-version
mimic how other projects set up this undocumented dependabot's feature
=> ci: remove comments in .python-version
