canonical/pycloudlib

pycloudlib/cloud.py, pycloudlib/ec2/cloud.py, requirements.txt
Add ec2.list_keys operation to allow for checking if keys exist.
It allows us to look before we leap before calling either delete_key
or upload_key.
=> ec2: add list_keys method

docs/clouds/ec2.md, examples/ec2.py, pycloudlib/ec2/cloud.py, pycloudlib/ec2/vpc.py
Refactor ec2.create_vpc method to get_or_create_vpc which will reuse existing VPCs if present.
Refactor VPC class to better represent the proxy class that it is:
* Add `VPC.create` method to create a new vpc providing a boto3 ec2.resource client, name/tag and optional ipv4_cidr
* Add `VPC.from_existing` taking the same boto3 ec2.resource client and and the vpc_id of an existing EC2 VPC.
* Simplify and decorate all @classmethods called by `VPC.create`
* Add a `name` property method which looks up the 'Name' tag associated with the VPC to avoid carrying that instance attribute around.
* `delete` now walks through all associated boto3 VPC resource properties and methods to perform deletion instead of relying on pycloudlib.ec2.VPC instance attributes for security groups, route tables, subnets …
=> ec2: use pre-existng vpc if available when create_vpc is called

pycloudlib/oci/__init__.py, pycloudlib/oci/cloud.py, pycloudlib/oci/instance.py
Add __inti__.py so oci submodule is recognized in the pycloudlib package
=> oci: add __init__ to include oci submodule in pkging

requirements.txt
Avoids the following error:
The conflict is caused by:
The user requested azure-mgmt-resource==10.1.0
azure-cli-core 2.9.1 depends on azure-mgmt-resource==10.0.0
No newer version of azure-cli-core is available.
=> requirements: downgrade the azure-mgmt-resource dep to 10.0.0

pycloudlib/azure/cloud.py, pycloudlib/azure/instance.py, pycloudlib/azure/util.py
Allow users to launch Azure pro images from both marketplace and snapshots of Azure pro virtual machines.
To support that, we had to add the `plan`field in the vm parameters dict.
To test these changes, I have used the following image ids:
```
Canonical:0001-com-ubuntu-pro-bionic:pro-18_04-lts
Canonical:0001-com-ubuntu-pro-focal:pro-20_04-lts
```
=> Add support for Azure pro images

examples/base_api.py, pycloudlib/azure/instance.py, pycloudlib/cloud.py, pycloudlib/ec2/cloud.py, pycloudlib/ec2/instance.py, pycloudlib/gce/cloud.py, pycloudlib/instance.py, pycloudlib/kvm/cloud.py, pycloudlib/kvm/instance.py, pycloudlib/lxd/cloud.py, pycloudlib/lxd/instance.py, pycloudlib/oci/cloud.py, pycloudlib/oci/instance.py, pycloudlib/util.py
The goal here is to have the base class be consistent with the implementing classes.
I've made the base cloud and instance classes officially inherit from ABC and added abstract decorators to all of the relevant methods/properties. This will give us more much detailed type/linting info and errors if we have a mismatch or unimplemented method in an implementing class.
I also changed all of the method signatures across the implementations to use the same API as the base class. Where certain APIs might request more to be passed in, the base class provides `**kwargs` that can be overridden.
Since none of the remaining TODOs are code-focused, I think this can be reviewed now.
TODO:
* Test for every cloud. As of right now I've only verified my changes on LXD
* Update …
=> Refactor api

pycloudlib/instance.py
This started by fixing a bug in the deleted code:
cloud-init status --wait 2&>1 > /dev/null
should have been:
cloud-init status --wait > /dev/null 2>&1
however now that Trusty reached EOL we can just assume that
`cloud-init status --wait` is available and drop the wait
logic based on polling runlevel(8).
=> Fix stdout+stderr redirection to /dev/null

pycloudlib/instance.py
In `uaclient` we are having a problem with connectivity issues regarding paramiko connect. One hypothesis that we have is that the connect get `stuck` and since we have no timeout on that operation, it hangs indefinitely. This PR is adding a timeout parameter to this operation.
Although this should be parametrized by all instance types, I think it is better to wait for #9 to land, to make that consistent. Also, we could also check if the timeout issue will actually fix the uaclient problem.
=> Add timeout to paramiko connect

pycloudlib/instance.py
With the current decorator order for the `name` method in the `instance` module we raise the following error when trying to run the code:
```python
File "/usr/lib/python3.6/abc.py", line 25, in abstractmethod
funcobj.__isabstractmethod__ = True
AttributeError: attribute '__isabstractmethod__' of 'property' objects is not writable
```
This is raised because the decorator order is incorrect.
=> Fix order of decorators in instance module

.pylintrc, pycloudlib/azure/cloud.py, pycloudlib/cloud.py, pycloudlib/ec2/cloud.py, pycloudlib/gce/cloud.py, pycloudlib/kvm/cloud.py, pycloudlib/oci/cloud.py, pycloudlib/tests/__init__.py, pycloudlib/tests/test_cloud.py, test-requirements.txt, tox.ini
Required because ua-tools CI already provides a timestamped tag, so we don't want pycloudlib to tack on a secondary timestamp suffix. Otherwise our tags get rejected.
See: https://travis-ci.org/github/canonical/ubuntu-advantage-client/jobs/723850613#L344
=> Cloud add timestamp suffix param and initial unit tests

.pylintrc, pycloudlib/instance.py, pycloudlib/tests/test_instance.py
`pycloudlib.util.subp`'s default behaviour is to raise an exception if
the command being executed exits non-zero.  Before this commit, this
meant that executing a command against a LXD or KVM instance that exited
non-zero would raise an exception (instead of returning a `Result`
object as other instances do).
Fixes: #30
=> instance: allow KVM/LXD commands to exit non-zero

pycloudlib/instance.py, pycloudlib/tests/test_instance.py
Doing everything within a single shell script makes it hard to
interrogate why failure was reported.  The refactored code will only run
the part of the shell script which is relevant to the system under test:
`cloud-init status --wait` if available, otherwise the while loop using
`runlevel`.
Also add tests for `_wait_for_system`.
=> instance: refactor _wait_for_system to reduce shell script complexity

pycloudlib/azure/instance.py, pycloudlib/ec2/instance.py, pycloudlib/gce/instance.py, pycloudlib/instance.py, pycloudlib/kvm/instance.py, pycloudlib/lxd/instance.py, pycloudlib/oci/instance.py, pycloudlib/tests/test_instance.py
This modifies BaseInstance.wait from an abstract to a concrete method
which calls `self._wait_for_start` then `self._wait_for_system`.  This
ensures that we will always call `self._wait_for_system` when `wait` is
called, while still allowing subclasses to define their own additional
waiting logic.
Any existing subclass `wait` implementations which only called
`self._wait_for_system` have been removed (as the superclass now
performs that itself).  The remaining implementations have been renamed
to `_wait_for_start` and have had any calls to `self._wait_for_system`
removed (as the superclass will now do that).
Fixes #35
=> instance: refactor BaseInstance.wait

pycloudlib/instance.py, pycloudlib/tests/test_instance.py
This means that the error message included in the raised `OSError` on
failure contains some information about the failure (rather than just
the dots that `--wait` causes to be emitted).
=> instance: add `--long` to `cloud-init status --wait` call

pycloudlib/oci/cloud.py
When launching an oci instance, there is a check to ensure the state is
RUNNING before it is returned. I removed the check because If wait=False
this won't work
=> Remove unnecessary oci RUNNING launch check

.pylintrc, requirements.txt, setup.py
As a library, pycloudlib should allow consumers to select precisely the versions of dependencies that they want to use. This commit achieves that by specifying lower (and where necessary, upper) bounds on the versions required, instead of specific versions.
It moves these specifications from `requirements.txt` to `setup.py`: per https://packaging.python.org/discussions/install-requires-vs-requirements/, this is the appropriate place for libraries to express their dependencies. `requirements.txt` will now install the local version of the library.
Fixes #41
Test that the integration tests work (to the same level as `master`) on:
The [`deps` branch in my repo](https://github.com/OddBloke/cloud-init/tree/deps) is the corresponding refactor of cloud-init's dependencies, and currently has this …
=> Stop depending on specific versions of dependencies

pycloudlib/lxd/cloud.py
We are only using the `images:ubuntu/16.04/cloud` when we are creating virtual machines. However, this is wrong, since we always need to use that machine, for containers and virtual machines. The reason for that is that other xenial images will not have the necessary requirements to allow the use of `lxc exec` commands
=> Set correct xenial image for LXD

pycloudlib/instance.py
See https://github.com/canonical/cloud-init/pull/664
=> Add sudo option to instance execute

pycloudlib/instance.py, pycloudlib/lxd/instance.py, pycloudlib/tests/test_instance.py
Currently, the `images:ubuntu/16.04/cloud` errors out when we try to run the `_wait_for_cloudinit`  method. If we retry on that first error, the instance is launched without an issue. To address that, we are relaxing the retry check we have on `_wait_for_cloudinit`
=> Retry cloudinit wait on all LXD instance types

pycloudlib/lxd/cloud.py
_build_necessary_profiles is called on every VM launch. Part of doing that is looking up the image being used to get the OS in use. If I've generated an LXD snapshot, that won't work, because I'm using a `local:` source, so I would like to cache the generated profile in cloud-init tests, thus requiring `build_necessary_profiles` to be part of the public API.
=> Make _build_necessary_profiles part of the public LXD API

.travis.yml
Our current travis build is running the cloud-init integration tests with the current cloud-init version. This is problematic
because some of the tests on cloud-init assume that we are using the most recent version of the package. To fix that, we
will be using the cloud-init package from our daily ppa to run the integration tests
=> Update travis to run cloudinit test with daily ppa

pycloudlib/lxd/instance.py
In ubuntu-advantage-tools, we require some LXD commands to be run as `non-root`. This PR changes the default behavior of LXD to run exec commands as non-root.
This will impact some `cloud-init` tests, but we already have a [PR](https://github.com/canonical/cloud-init/pull/664) to handle that
=> Run lxc commands as non root by default

pycloudlib/lxd/cloud.py, pycloudlib/lxd/defaults.py
Per a comment from stgraber[0], the config disk is "only used for legacy images that do not have the agent".  As the agent is present in focal and later, instances using these profiles do not need to attach the config disk. (This is pertinent because until https://github.com/lxc/lxd/pull/8182 is released, we cannot use network configuration via the config disk.)
This change also switches us to using the KVM disk images for focal and later, for full agent support.
[0] https://github.com/lxc/lxd/issues/7292#issuecomment-733143079
=> lxd: don't attach config disk to focal+ LXD VMs

examples/gce.py, pycloudlib/cloud.py, pycloudlib/gce/cloud.py, pycloudlib/lxd/cloud.py
Currently, there is no way for the GCE cloud instance to create ssh keys to be used on the instances. We are now adding that possibility. Also, we are changing the user related to the ssh key from admin to ubuntu, to be consistent with the ssh behavior of other cloud instances
=> Allow GCE cloud to create ssh keys

examples/gce.py, pycloudlib/gce/cloud.py
Right now, we need to explicitly set some environment variables to successfully create GCE instances. We are now setting those variables inside the GCE cloud
=> Make GCE cloud set environment variables

pycloudlib/instance.py
This allows users to specify keys with passphrases, but clearly warns
them about what may happen if they haven't added the key to an SSH agent
(which removes the need for a passphrase when this code runs).
Fixes #82.
=> instance: convert SSH key passphrase error to a warning

.travis.yml
This is required for us to detect the version of the image under test,
which is required to skip tests which we expect to fail on that image.
=> .travis.yml: install distro-info for cloud-init tests

pycloudlib/oci/cloud.py
Use a helper property to read SSH file contents instead of doing it
ourselves.
=> oci: use existing KeyPair helper

examples/az.py, pycloudlib/azure/cloud.py
pubkey content returned by Azure's SDK via
azure.mgmt.compute.ComputeManagementClient.ssh_public_keys.generate_key_pair
will contain CRLF \r\n at a 64 character line-width creating an invalid
ssh-rsa pub key format.
ssh-rsa <pub_key_content_part1>\r\n<pub_key_content_part2>\r\n<etc>
OpenSSH doesn't like this which results in ssh Unauthorized errors when
trying to ssh using your now local/invalid public_key.
Fixes: #88
To test:
* failure path without this PR
```bash
tox -e pylint
.tox/pylint/bin/python3 example/az.py    # get Unauthorized errors
cat pub_test.pem  # see newlines in ssh-rsa content at 64 char width
```
* success path use this PR
```bash
tox -r -e pylint
.tox/pylint/bin/python3 example/az.py
cat pub_test.pem # see a single line with ssh-rsa content
```
=> azure: create_key_pair should strip CRLF from multi-line pub keys

pycloudlib/lxd/cloud.py, pycloudlib/lxd/tests/test_cloud.py
On LXD, we use a regex to extract the ubuntu release from a image id. We try to find either the base release
name on the image id, like focal, or the version number, like 20.4. However, if the image id has a timestamp on it we could accidentally match the timestamp value instead of a valid version string. The reason for that is because
we are not escaping the dot part of the version string.
For example, for this image id:
`local:ubuntu-behave-image-build--vm-focal1610458065934836-snapshot`
Using the following regex:
`(.*ubuntu.*(?P<release>(focal|bionic|xenial|20\.04|18\.04|16\.04)).*)`
We are matching the timestamp part `16104`
=> Fix regex that extracts release from image id

pycloudlib/gce/cloud.py, pycloudlib/oci/cloud.py
Stop requiring to pass in project for gce and compartment for oci
=> Get defaults from CLI for GCE and OCI if not provided

pycloudlib/gce/cloud.py
When we are launching an image, we do not bind it to a service account, even if we are using a service account credential to launch the images. This is problematic because some of our vms need that to work properly. For example, the recent gcp pro machines requires that bind to allow uaclient to auto-attach on them. To fix that, we are now performing that bind if the user provides a service_account_email to the gce client.
@OddBloke I think this is a less restrictive approach than the one I had before
=> Set service account email for gce instance

pycloudlib/lxd/cloud.py, pycloudlib/lxd/tests/test_cloud.py
Both images: and ubuntu[-daily]: Ubuntu LXD images are published with metadata that describes the OS and release of the contained image.  This metadata is retained across image snapshots.
Instead of relying on naming conventions and regexes to determine the release of a LXD image, this PR calls `lxc image info` and parses the emitted YAML to find the apropos release.
This also includes a couple of prerequisite changes: there was a naming inconsistency that made it difficult to reason about this issue, and we were handling image IDs inconsistently (some public APIs would prepend the daily remote if no remote was specified, others wouldn't).
Fixes: #95
=> lxd: use `lxc image info` for release name determination

pycloudlib/gce/cloud.py, pycloudlib/oci/cloud.py
GCE simply had a bug: it didn't call `instance.wait()`.
OCI's behaviour is changed somewhat: we now unconditionally wait for the instance to be `RUNNING` and `wait=True` controls whether `instance.wait()` is called.
=> align GCE and Oracle launch wait behaviour with other clouds

pycloudlib/oci/cloud.py
Per their changelog[0], list_subnets went from taking `vcn_id`
positionally to taking it as a keyword argument: this commit follows
that.
[0] https://github.com/oracle/oci-python-sdk/blob/master/CHANGELOG.rst#breaking-11
Fixes: #106
=> oci: fix API call broken in oci 2.18.0

pycloudlib/gce/cloud.py, pycloudlib/oci/cloud.py
I previously made OCI's wait=True behaviour consistent with GCE, but
that means they are inconsistent with the other clouds supported by
pycloudlib.  This commit aligns their behaviour with the other clouds.
Specifically, the "wait for instance start" calls made to the cloud are
no longer unconditional, and instead are only executed if wait=True
before instance.wait() is called.
=> oci/gce: only perform cloud-native wait in launch if wait=True

.travis.yml, pycloudlib/lxd/cloud.py, pycloudlib/lxd/instance.py, pycloudlib/lxd/tests/test_instance.py, pycloudlib/tests/test_instance.py
Analysis performed (and captured in #112) indicates that accessing LXD
instances via SSH rather than via `lxc exec` leads to faster test
execution, and also brings LXD's default behaviour in line with the
default behaviour of other clouds.
This commit introduces a `execute_via_ssh` parameter and instance
variable, which are used by `execute()` to determine whether to connect
to the instance via SSH, or use `lxc exec`.  The default value of
`execute_via_ssh` is `True`.
(Prior to this commit, we would execute via SSH but only if we had a key
manually set against the instance, leading to inconsistencies in
behaviour depending on local configuration.  This also addresses that.)
Fixes: #112
=> lxd/instance: use SSH by default, allow switching to `exec`

pycloudlib/lxd/cloud.py
Instead of merging them into whatever user-data is specified by the
pycloudlib consumer: this has lead to issues when intentionally invalid
user-data is specified (because the SSH keys are ignored), and would
also cause issues if the consumer's user-data specified its own
ssh_authorized_keys (because they would be overriden).
Fixes: #98
=> lxd: pass SSH keys as meta-data

pycloudlib/instance.py, pycloudlib/lxd/instance.py, pycloudlib/tests/test_instance.py
When investigating the relative performance of execution methods for #114, I found that a lot of our slow launch speeds were due to long sleeps between retries. This PR tweaks a variety of them, and fixes #111 as well.
=> pycloudlib: increase a variety of retry frequencies

pycloudlib/lxd/defaults.py
When we create Xenial and Bionic lxd vm instances through pycloudlib, we need to provide a script to install the lxd-agent
on those machines. Recently, one of the services that was being started in this script was dropped from lxd, lxd-agent-9p. We are
now updating the script to remove references to that service.
This is the new script being used:
```sh
#!/bin/sh
if ! grep lxd_config /proc/mounts; then
mkdir -p /run/lxdagent
mount -t 9p config /run/lxdagent
VIRT=$(systemd-detect-virt)
case $VIRT in
qemu|kvm)
(cd /run/lxdagent/ && ./install.sh)
umount /run/lxdagent
systemctl start lxd-agent
;;
*)
esac
fi
```
And we can see that lxd has dropped support for the `lxd-agent-9p` service on this commit:
https://github.com/lxc/lxd/commit/2d013dfbeb4d10575989ab07e0a69022a6f9aa0b
=> Update lxc-setup script on lxd vm instances

examples/az.py, pycloudlib/azure/cloud.py
Azure was the only cloud that didn't include `instance_type` in it's launch.
Note that I DIDN'T put it at the end to keep as to keep it consistent with the other launch APIs. If people were passing args in a particular order to Azure launch, this will break them.
=> Support 'instance_type' for Azure instances

docs/clouds/openstack.md, examples/base_api.py, pycloudlib/__init__.py, pycloudlib/openstack/cloud.py, pycloudlib/openstack/instance.py, pycloudlib/openstack/tests/test_cloud.py, pycloudlib/openstack/tests/test_instance.py, setup.py
At this point I think the basic functionality is usable and reviewable.
Everything in the base_api.py test works, so the basics all work. I intentionally didn't add an example since all clouds should share the same base API right now. We should really only need one example unless we want to showcase specialized use cases of a specific cloud.
=> Initial openstack support

pycloudlib/lxd/cloud.py, pycloudlib/lxd/defaults.py, pycloudlib/lxd/tests/test_cloud.py, pycloudlib/lxd/tests/test_defaults.py
Currently, when we update a LXD vm profile we may have not see it reflected on subsequent runs because we do not generate a new profile if there is one with the same name on the system. To avoid that, we are now adding a version suffix to the profile name while also creating a md5sum test that will fail if we update the profile content but do not update the md5sum in the test.
PS: The way our test is structure does not prevent that a user may modify the profile, change the md5sums but do not bump the version name on the profile. However, I am proposing a guideline to incrementally add new profile version to the md5sum dict. I believe this documentation can help us reviewing future PRs that will change the profile. But if anyone has an idea to programmatically check that the version was …
=> Update naming convetion for LXD vm profiles

docs/conf.py
Per https://recommonmark.readthedocs.io/en/latest/, this is the
appropriate way to enable recommonmark's Markdown handling for Sphinx
versions newer than 1.3.
=> doc: update recommonmark configuration

pycloudlib/instance.py
We are observing that a lot of tests that use pycloudlib are failing to due errors reading SSH protocol banner. Since we
cannot consistently reproduce those errors, we believe this should be related to a timeout issue. To address that we are now setting
the banner_timeout variable when we run paramiko connect method.
As an example, here is one Jenkins test that is being affected by this issue:
https://jenkins.canonical.com/server-team-jenkins-private/blue/rest/organizations/jenkins/pipelines/github-ci/pipelines/ubuntu-advantage-client/branches/PR-1414/runs/6/nodes/128/steps/153/log/?start=0
=> Add banner timeout for paramiko connect

pycloudlib/lxd/cloud.py, pycloudlib/lxd/defaults.py, pycloudlib/lxd/instance.py, pycloudlib/lxd/tests/test_defaults.py, pycloudlib/lxd/tests/test_instance.py
Currently, LXD xenial virtual machines use a special image to allow supporting installing lxd-agent on the vm and
run commands with lxc exec. Since we are now running all the commands with ssh by default, we don't need to support that xenial image anymore. The implication now is that xenial vm will not be able to run lxc exec commands
=> Drop support for xenial vstock image

pycloudlib/lxd/instance.py, pycloudlib/lxd/tests/test_instance.py
lxd.ip: better instance name match and parsing of lxc ls output
Use exact name matching via lxc ls "^<name>%" to avoid matching
multiple vms with common name prefix.
Add try/except blocked to handle, ignore and retry on unexpected
responses while lxc brings up the instance networking.
Add some logging for unparseable output so we can better handle
those cases if they result in irresolvable instance state.
Raise TimeoutError if our 150 retries are exhausted
Fixes: #129
=> lxd.ip: better instance name match and parsing of lxc ls output

pycloudlib/gce/cloud.py
This matches the behaviour of other platforms, which raise either
IndexError or ValueError to indicate that no daily/release image has
been found.  This fixes specifying a non-default GCE image in
cloud-init's integration testing.
(This isn't ideal, of course, but this commit at least makes it
consistent.)
=> gce: raise IndexError if no image found

pycloudlib/ec2/instance.py
On EC2, console log output is not available immediately after launching
an instance: we've seen it take up to 2 minutes for the API to start
returning content.  Instead of, arguably incorrectly, claiming that
there is no console output in these cases, we retry for up to 3 minutes
until we get _some_ content.
=> ec2: wait for console log output

docs/clouds/azure.md, pycloudlib/azure/cloud.py, pycloudlib/instance.py, pycloudlib/lxd/cloud.py, pycloudlib/lxd/tests/test_cloud.py, pycloudlib/tests/test_instance.py
We have dropped the support for trusty in [ubuntu-advantage-client](https://github.com/canonical/ubuntu-advantage-client/pull/1611). Since this is the only project we are aware that had the need for trusty lxd support, we are dropping that support from pycloudlib.
PS: I have kept the trusty check on LXD VMs, to alert the user that a trusty vm cannot be launched, but I can drop this as well if needed
=> Drop trusty support for launching lxd instances

pycloudlib/openstack/instance.py
Openstack wants to be cool like ec2 (see #143).
=> openstack: wait for console log output

examples/base_api.py, examples/oci.py, pycloudlib/oci/cloud.py
availability_domain used to be able to be inferred from the subnet.
Now it is required to be passed manually.
https://docs.oracle.com/en-us/iaas/tools/python/2.38.3/api/core/models/oci.core.models.Subnet.html#oci.core.models.Subnet.availability_domain
Fixes #138
=> Make OCI's availability domain required (SC-59)

.github/workflows/ci.yaml
Specifying `pull_request` will still build every time there is a new push to the pull request. When we specify `push`, we get double builds for every PR.
=> Run Pycloudlib CI GH action only on pull_request

pycloudlib/instance.py, pycloudlib/lxd/instance.py, pycloudlib/lxd/tests/test_instance.py, pycloudlib/oci/instance.py, pycloudlib/tests/test_instance.py
List of changes are in the respective commits (please don't squash merge them). If this PR is approved I'll take care of getting PR commits getting squashed into the right commit.
In general, moved all the SSH retry logic to the wait for boot section. The connection timeout should take care of the random network blips.
I also provided a base method for restart. Every cloud that issued a restart signal then waited for boot (including the fancy ec2 implementation) had occasional reboot issues. Are there any situations we know of where we'd need to explicitly send a restart signal rather than just a shutdown then start?
I also fixed some cloud-specific boot issues.
=> Move SSH retry logic to boot wait method (SC-58)

pycloudlib/lxd/defaults.py, pycloudlib/lxd/tests/test_defaults.py
On xenial we don't need the lxd-agent anymore, however we do need additional cloud-init config to be added into the profile. We are not splitting the cloud-init behavior from lxd-agent one
=> update lxd xenial profile to not install agent

pycloudlib/lxd/instance.py
On xenial LXD vms, we don't install the lxd-agent. Therefore we cannot properly run the _wait_for_instance_start method. To fix that, we will not run that method on xenial LXD vms
=> Don't run wait_for_instance_start on xenial LXD vms

pycloudlib/oci/instance.py
Whoops, when I removed the "start/stop" commit on the timeout PR, I forgot to update OCI to also sync before restart.
Also updated the description to be slightly less aggressive :joy:
=> Sync OCI on both shutdown and restart (SC-120)

.github/workflows/ci.yaml
This reverts commit 79cdc8a832a82e82293ec2288e86b0d1b7374481.
When running CI on: [push, pull_request] and commits are pushed to a PR
there is the impression that CI runs twice, once for the "push" and once
because the PR got updated. This is actually not true as the run is not
the same:
- The push-triggered CI run happens on the branch as it is;
- The pull_request-triggered CI run happens on the *merge* of the PR
to its target branch.
so the second is not really a duplicate. In particular in the pycloudlib
repository we didn't set the "Require branches to be up to date before
merging" GH option, so merges are not always quasi-fast-forwards, and the
two CI runs can differ.
=> Run Pycloudlib CI GH action on both 'push' and 'pull_request'

pycloudlib/ec2/instance.py
We're still getting failures on ec2 due to console logs not being available. E.g., https://jenkins.ubuntu.com/server/view/cii-pytest/job/cloud-init-integration-ec2-focal-daily/5/console
I want to try upping the wait time to 5 minutes, and if that doesn't work, restricting the test to only run on LXD until we can fix what's wrong here.
=> ec2: Increase console wait time to 5 minutes

pycloudlib/lxd/instance.py, pycloudlib/lxd/tests/test_instance.py
Ephemeral instances are properly deleted by lxd when they are stopped. Because of that we are now shutting down ephemeral instances when a user calls delete on them.
=> lxd: use shutdown to delete ephemeral instances

pycloudlib/lxd/cloud.py, pycloudlib/lxd/instance.py, pycloudlib/lxd/tests/test_instance.py
lxd: ephemeral instance shutdown should not wait for STOPPED state
Since lxd will destroy an ephemeral instance after shutdown, don't
call wait_for_stop() as it'll timeout on inability to find any
instance information from `lxc info <name>`
=> Lxd shutdown no wait

examples/lxd.py, pycloudlib/lxd/instance.py
During the snapshot call, we shutdown the base instance before creating the snapshot. This approach doesn't work for ephemeral instances, because they get deleted after the shutdown operation. We are now updating the snapshot function to allow ephemeral instances to be snapshot.
Fixes #159
=> Allow snapshot for LXD ephemeral instances (SC-321)

pycloudlib/gce/cloud.py
When initializing GCE fallback to the GOOGLE_APPLICATION_CREDENTIALS and
GOOGLE_CLOUD_PROJECT environment variables if credentials_path or
project are not specified.
=> gce: fallback to GOOGLE_CLOUD_PROJECT if project is not specified

pycloudlib/openstack/instance.py, setup.py
```
Revert openstack pin and fix call site
In 85a22bd7 I pinned the openstack version because I thought a later
version of the API changed. In actuality, I was passing an unneeded
argument. Older versions of the API didn't raise on it, but newer
versions do, so revert the pin and fix the API call.
```
Notice that none of the openstack API versions we use have a "node_id":
https://docs.openstack.org/openstacksdk/victoria/user/resources/network/v2/port.html#openstack.network.v2.port.Port
https://docs.openstack.org/openstacksdk/wallaby/user/resources/network/v2/port.html#openstack.network.v2.port.Port
https://docs.openstack.org/openstacksdk/xena/user/resources/network/v2/port.html#openstack.network.v2.port.Port
https://docs.openstack.org/openstacksdk/latest/user/resources/network/v2/port.html …
=> Revert openstack pin and fix call site

docs/Makefile, docs/conf.py
In 49dbce2cac5b9682435ee58dfa902efff7e9ca68 , I removed the api-docs from version control thinking they get regenerated every readthedocs build. They do not (and were years out of date). This change lets us auto-generate the API docs during the readthedocs build.
Current API docs: https://pycloudlib.readthedocs.io/en/latest/api.html# (because I removed them :smile: )
Temporary API docs using this branch: https://pycloudlib.readthedocs.io/en/auto-apidoc/api.html
=> docs: auto-generate the API docs (SC-656)

.pylintrc, examples/az.py, examples/gce.py, examples/lxd.py, pycloudlib/azure/cloud.py, pycloudlib/instance.py, pycloudlib/key.py, pycloudlib/util.py, setup.py, tox.ini
This solves a E1136 false positive with Python 3.9 [1], but the code
needs some changes to test clean.
[1] https://github.com/PyCQA/pylint/issues/3882
=> tox: bump pylint to 2.12.2

pycloudlib/lxd/instance.py
Apparently 300s are not enough when the host machine is busy, in
particular Bionic seems to be likely to hit the 300s timeout.
=> lxd vm: wait up to 600s for the agent to come up

pycloudlib/azure/cloud.py
Add missing Jammy image support for Azure.
Fixes Jenkins errors of the type
22:37:56 E           Message: Property id 'jammy' at path 'properties.storageProfile.imageReference.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'.
And pycloudlib errors of 
`ValueError: No Ubuntu release image found for None. Expected one of: xenial bionic focal groovy hirsute`
To test:
1. setup ~/.config/pyclcoudlib.toml for the azure section based on `az ad sp create-for-rbac --sdk-auth`
2. Attempt to find a "jammy" daily image
```bash
tox -e pytest
echo > test.py <<EOF
import pycloudlib
import logging 
def doit():
logging.basicConfig(level=logging.DEBUG)
client = pycloudlib.Azure(tag="azure") …
```
=> azure: add jammy daily image support

setup.py
In the logs of a failed test:
```
21:50:41     def get_azure_cli_credentials(resource=None, with_tenant=False):
21:50:41         """Return Credentials and default SubscriptionID of current loaded profile of the CLI.
21:50:41     
21:50:41         *Disclaimer*: This method is not working for azure-cli-core>=2.21.0 (released in March 2021).
21:50:41         It is now recommended to authenticate using https://pypi.org/project/azure-identity/ and AzureCliCredential.
```
I think this "fix" will get our tests passing, but since this has been depreciated it looks like we'll eventually need to switch to azure-identity.  Alternatively we could add the azure-identity dependency and modifications right now, if preferred.
=> set max azure-cli-core version

pycloudlib/azure/cloud.py
We don't expect to see hirsute in the image list for Jammy.
Also LTS images for Azure typically have -lts in image name
suffix.
```bash
az image list --alls --publisher Canonical | tee azure.images
grep server-jammy  azure.images
cat >test.py <<EOF
import logging
import pycloudlib
def demo():
client = pycloudlib.Azure(tag="azure")
image_id = client.daily_image(release="jammy")
instance = client.launch(
image_id=image_id,
instance_type="Standard_DS2_v2",  # default is Standard_DS1_v2
)
instance.delete()
if __name__ == "__main__":
logging.getLogger("adal-python").setLevel(logging.WARNING)
logging.getLogger("cli.azure.cli.core").setLevel(logging.WARNING)
logging.basicConfig(level=logging.DEBUG)
demo()
EOF
tox -e pytest
.tox/.testenv/bin/python3 test.py
Message: The platform image …
```
=> azure: fix cut-n-paste image issue

pycloudlib/lxd/instance.py
The '-f' flag is no longer available. Long options are better anyway
because they are more readable.
=> Stop using short options on "lxc list"

pycloudlib/ec2/cloud.py
```
Bump EC2 instance type
Updates the default ec2 instance type to t3.micro as it supports
IPv6 metadata while also being faster and cheaper than t2.
```
=> Bump EC2 instance type (SC-924)

pycloudlib/cloud.py, pycloudlib/gce/cloud.py, pycloudlib/gce/util.py, tox.ini
config: expand environment variables in paths
This is particularly helpful in Jenkins where file credentials are put
in a random location which exposed via an environment variable, which
we can now specify in the toml config.
=> config: expand environment variables in paths (SC-941)

pycloudlib/azure/cloud.py
Previously, released_image() pointed to daily_image() on Azure. This
commit allows us to launch released images as well.
Fixes #96
=> Include Azure released images (SC-943)

pycloudlib/ec2/instance.py
The test is not expensive, we can lower the sleep interval.
This matters when gathering post-reboot metrics (e.g. time to first
successful ssh login).
=> ec2 restart(): sleep less when checking if boot_id changed (SC-976)

pycloudlib/instance.py, pycloudlib/tests/test_instance.py
AWS EC2 metal instances can take over 20 minutes to start or restart.
=> wait_for_execute(): wait up to 40 minutes (SC-977)

pycloudlib/ec2/instance.py
```
Get latest console_log from ec2
Without this, retrieving the console log can take up to 20 minutes.
Requires Nitro, but all of our ec2 instances already do.
```
See https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Instance.console_output
=> Get latest console_log from ec2 (SC-982)

pycloudlib/cloud.py, pycloudlib/lxd/cloud.py
Currently if a streams query finds no results, we'll get an
'IndexError: list index out of range' exception at the call site.
This commit adds a more meaningful exception if no images are found from
the streams query.
E.g., from a kinetic run (which hasn't yet hit dailies): https://jenkins.canonical.com/server-team/view/cloud-init/job/cloud-init-integration-kinetic-lxd_container/3/consoleFull
Now we should get a message like:
```
ValueError: No images found matching filters: ['combined_squashfs_sha256=kinetic']
```
=> Raise exception when no results from streams query (SC-996)

pycloudlib/lxd/cloud.py, pycloudlib/lxd/defaults.py, pycloudlib/lxd/tests/test_defaults.py
For every new Ubuntu series, we have been creating a new LXD VM profile.
Since the profiles for the past few releases have been the same, we
should be able to a default profile from now on with exceptions for
Xenial and Bionic.
=> Create default LXD VM profile

setup.py
Set max version of google-api-python-client to < v2.49.0
Set max version of protobuff to < 3.12.0
google-api-python-client v2.49.0 was released yesterday, and it looks like this updated a protobuf dependency to require Python 3.7. 
Error log in cloud-init:
```
Collecting protobuf>=3.12.0
Downloading https://files.pythonhosted.org/packages/6c/be/4e32d02bf08b8f76bf6e59f2a531690c1e4264530404501f3489ca975d9a/protobuf-4.21.0-py2.py3-none-any.whl (164kB)
ERROR: Package 'protobuf' requires a different Python: 3.6.10 not in '>=3.7'
=================================== log end ====================================
ERROR: could not install deps [-r/home/travis/build/canonical/cloud-init/integration-requirements.txt]; v = InvocationError('/home/travis/build/canonical/cloud-init/.tox/integration-tests-c …
```
=> pin google-api-python-client

pycloudlib/util.py
OCI relies on UBUNTU_RELEASE_VERSION_MAP for image stream lookup.
Add relevant known Ubuntu release maps to aid in image discovery.
=> util: update UBUNTU_RELEASE_VERSION_MAP for oci

setup.py
protobuf dropped support for Python 3.6 in version 3.20, so we can allow
anything older than that.
As of today google-api-python-client's README.md [2] says that "Python
3.6, 3.7, 3.8, 3.9 and 3.10 are fully supported and tested", so we
should be safe without an upper bound.
[1] https://github.com/protocolbuffers/protobuf/commit/301d315dc4674
[2] https://github.com/googleapis/google-api-python-client/blob/b698f9c/README.md
=> dependencies: relax versioned dependencies (SC-1090)

examples/oci.py, pycloudlib/oci/instance.py
OciInstance: Implement network interface methods
- Implement `add_network_interface` and `remove_network_interface`.
- Fix example
=> OciInstance: Implement network interface methods

pycloudlib/oci/cloud.py
There can be multiple subnets in a virtual cloud network (VCN).
Typically we see 3 subnets in an availability_domain like ua-ashburn-1:
- US-ASHBURN-AD-1
- US-ASHBURN-AD-2
- US-ASHBURN-AD-3
pycloudlib must select the appropriate subnet matching the specific
availability_domain and not just source the first subnet at index 0.
Wrong subnet ID results in 400 erros from python SDK or UI dashboard
errors such as:
A problem occurred while preparing the instance's VNIC.
((400, InvalidParameter, false)
Parameter 'availabilityDomain' does not match.
VNIC has 'iad-ad-3' while the subnet has 'iad-ad-1'
(opc-request-id: dummyRequestId))
=> oci: select proper subnet matching availability_domain

pycloudlib/ec2/cloud.py
On AWS, the location of the Pro FIPS machine starts with `ubuntu-pro-fips-server`. We are updating our name filter to address that.
=> aws: add support for pro fips machine

pycloudlib/cloud.py, pycloudlib/gce/cloud.py
Test the before and after with 
```python
import logging
import pycloudlib
from pycloudlib.cloud import ImageType
logging.basicConfig(level=logging.DEBUG)
gce = pycloudlib.GCE(tag="test")
for r in ["xenial", "bionic", "focal", "jammy", "kinetic"]:
gce.daily_image(r, image_type=ImageType.GENERIC)
for r in ["xenial", "bionic", "focal", "jammy"]:
gce.daily_image(r, image_type=ImageType.PRO)
for r in ["bionic", "focal"]:
gce.daily_image(r, image_type=ImageType.PRO_FIPS)
```
You may need to add a logging statement to see the image name/creation date returned before this commit.
Before this commit, the fetched gce xenial image was out of date (from 2018).
This also changes all gce LTS images to be the latest **daily** image as implied by the method name `daily_image`.
=> gce: always fetch latest image

pycloudlib/azure/cloud.py, pycloudlib/cloud.py, pycloudlib/ec2/cloud.py, pycloudlib/gce/cloud.py, pycloudlib/oci/cloud.py, pycloudlib/openstack/cloud.py
Removes the requirement for pycloudlib and OCI config files to be in a
fixed path so pycloudlib can operate as a library. This allows specifying
parameters for the clouds independently of the config files, facilitating
integration with automated pipelines.
=> Dynamic config support

examples/gce.py, pycloudlib/gce/cloud.py, pycloudlib/gce/tests/__init__.py, pycloudlib/gce/tests/test_cloud.py, test.py
For GCE, before these changes, you might end up with an arm image when you wanted an amd image, or vice versa. This commit adds a new `arch` param to the gce `daily_image` method using the same signature as the ec2 `daily_image` which also takes an `arch` kwarg.
Test it with the following script:
```python
import logging
import pycloudlib
from pycloudlib.cloud import ImageType
logging.basicConfig(level=logging.DEBUG)
gce = pycloudlib.GCE(tag="test")
for a in ["x86_64", "arm64"]:
for r in ["kinetic", "jammy", "focal", "bionic", "xenial"]:
gce.daily_image(r, image_type=ImageType.GENERIC, arch=a)
```
Notice that xenial doesn't have an arm image, and there are no arm images for pro.
=> gce: filter daily_image by arch

pycloudlib/azure/cloud.py, pycloudlib/cloud.py, pycloudlib/ec2/cloud.py, pycloudlib/gce/cloud.py, pycloudlib/lxd/cloud.py, pycloudlib/oci/cloud.py, pycloudlib/openstack/cloud.py
Adds kwargs support for all oci operations.
Example usage: Oracle's SDK has retry strategies that can be used for most operations. Even though some of them (like launch_instance) do not retry by default, a retry strategy can be specified.
=> feat(oracle): add kwargs for oci operations

pycloudlib/lxd/instance.py, pycloudlib/lxd/tests/test_instance.py
This (straw man) approach selects the non-lxd bridge between two interfaces. It solves the problem where the second interface is created via nested instances. I'm fine if we'd rather reject this solution in favor of something less quick and dirty.
=> lxd: support multiple interfaces for lxd bridges

pycloudlib/azure/util.py, pycloudlib/instance.py, pycloudlib/tests/test_instance.py
When no 'az' command is installed, avoid relying on a default client created by:
client = resource(credential, subscription_id=subscription_id)
On systems without az command line client, the default client will later fail with messages like to following:
azure.identity._exceptions.CredentialUnavailableError:
Azure CLI not found
=> azure: if az command absent, use explicit config params

pycloudlib/lxd/instance.py, pycloudlib/lxd/tests/test_instance.py
There are cases where ephemeral instances are not running and not
automatically deleted, e.g. when they are in ERROR state. Let's
just call `lxc delete` as we do for non-ephemeral images, and trust
lxd to do the right thing.
This is a partial revert of 0869d07b7894d985e183be957ae8318aae667c00.
=> lxd: delete ephemeral instances using lxc delete

pycloudlib/ec2/cloud.py
In https://github.com/canonical/pycloudlib/commit/efcdf6712bbbdf526a98545b091f897d484e63a0, `daily_image()` was changed to raise an `Exception` when an image is not found. Before that commit this code path was raising a `ValueError` later in `_streams_query()`.
This change broke cloud-init integration test functionality which allowed booting [arbitrary AMIs](https://github.com/canonical/cloud-init/blob/dcd8413c8874b615fc7e3c54da15f6ed5d8dedc7/tests/integration_tests/clouds.py#L132). Switch the raised exception back to `ValueError`.
=> [bugfix] Don't raise Exception

examples/base_api.py, pycloudlib/azure/cloud.py, pycloudlib/azure/util.py, pycloudlib/cloud.py, pycloudlib/config.py, pycloudlib/ec2/cloud.py, pycloudlib/gce/cloud.py, pycloudlib/ibm/cloud.py, pycloudlib/ibm/instance.py, pycloudlib/lxd/cloud.py, pycloudlib/oci/cloud.py, pycloudlib/oci/instance.py, pycloudlib/oci/utils.py, pycloudlib/openstack/cloud.py, pycloudlib/util.py, pyproject.toml, tox.ini
Enable mypy type checking and add more type definitions.
Fix bug in OciInstance.add_network_interface, discovered
by mypy. In a previous refactoring, we factor out the
oci.utils.get_subnet_id function to be used in
oci.cloud and oci.instance. This function does need the
availability_domain but OciInstance had not that attribute.
availability_domain added to OciInstance and fix the bug.
=> mypy: add type checking

.github/dependabot.yml, dev/requirements.txt, tox.ini
GH actions and lint requirements will be try to be updated in autogenerated PRs.
=> CI: add dependabot.yml to auto-update dependencies

dev/.python-version
Desired commit message:
```
dependabot: fix minimum python version #245 
```
Being the dependabot pip configuration pointing to `dev/`, it is not able to know the minimum required python version. See: https://github.com/canonical/pycloudlib/pull/244
Info on the topic: https://github.com/dependabot/dependabot-core/issues/1455
This burden could be simplified if we move to a pep-0517 compliant build system, as dependabot plays much nicer with `setup.cfg` configs. (We will have to do that at some point as the `setup.py` format is deprecated)
=> dependabot: fix minimum python version

pycloudlib/lxd/instance.py, pycloudlib/lxd/tests/test_instance.py
Extend LXD instance ip parsing to detect
nics with global address an no hostname.
Previously, nics without a hostname were ignored.
This config has been found on instances with bonds
and bridges.
=> lxd: fix ip parsing

dev/.python-version
Add fully qualified python version for dependabot
=> ci: fix min py version for dependabot

pycloudlib/oci/cloud.py
An [OSError](https://docs.python.org/3/library/exceptions.html#OSError) is not the correct exception to raise when connection to an instance times out, so a new custom exception for this was added. If a timeout occurs, the orphaned instance will now be deleted from oracle.
Also added type hinting to some methods that manage instances since sometimes these returns would be treated as BaseInstance instead of OciInstance.
=> (oracle) reuse retry strategy

examples/az.py, examples/ec2.py, examples/gce.py, examples/lxd.py, pycloudlib/azure/cloud.py, pycloudlib/cloud.py, pycloudlib/ec2/cloud.py, pycloudlib/gce/cloud.py, pycloudlib/lxd/_images.py, pycloudlib/lxd/cloud.py, pycloudlib/oci/cloud.py, pycloudlib/oci/instance.py, pycloudlib/oci/utils.py, pycloudlib/types.py, tests/integration_tests/oracle/test_launch.py, tests/integration_tests/oracle/test_utils.py, tests/integration_tests/test_public_api.py, tests/unit_tests/ec2/test_cloud.py, tests/unit_tests/gce/test_cloud.py, tests/unit_tests/lxd/test_cloud.py, tests/unit_tests/lxd/test_images.py, tests/unit_tests/oci/test_instance.py, tests/unit_tests/oci/test_utils.py, tests/unit_tests/test_types.py
This PR seeks to add the ability to uniformly identify and specify networking config across clouds, with initial sweeping implementation being made to Oracle cloud. 
The creation of a new `NetworkingType` enum and a `NetworkingConfig` dataclass should hopefully make it easy and standardized to represent networking for an instance or any of its NICs across clouds.
- Ran the new integration tests I wrote:
- `tox -e integration-tests -- tests/integration_tests/oracle/test_launch.py`
- `tox -e integration-tests -- tests/integration_tests/oracle/test_utils.py`
- Ran the full `test_public_api` CI locally (`tox -e integration-tests-ci`)
- Added significant unit test coverage over modified oracle functions relating to networking configs
- Ran coverage locally and compared with my changed code and …
=> V11 - add networking config types
